# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83356afd06bb9fb6456ba2dab11784f94426a1584b3b153792d89c147fe437c62f96eb6be1e166076e844081a2082531f0370b7155175b5bc553fd0a992eb8f6

test:
  secret_key_base: 6275f1fa62df468412f9bf735c9c96fc11cbadd768b9dd9f8e375b71f6b810510093ab0c88e90143b520389a7aaa160c4e2ab83cc2c68ecb6735c978a0a91dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
